# Site settings

title: Atmorojo
name: Atmorojo
email: satmo54@gmail.com
description: "I Write Codes and Fancy Letters"

baseurl: "" # the subpath of your site, e.g. /blog/

twitter_username: atmorojo
github_username: atmorojo
instagram_username: atmorojo

url: https://atmorojo.github.io
paginate: 10
paginate_path: "posts/:num"
excerpt_separator: '[[ more ]]'

markdown: kramdown

permalink: /:year/:month/:day/:title/

exclude: [node_modules]
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
    noscript: false
