# Site settings
title: Atmorojo
name: Atmorojo
copyright_name: Atmorojo
header-img: img/home-bg.jpg
email: satmo54@gmail.com
description: "I Write Codes and Fancy Letters"

baseurl: "" # the subpath of your site, e.g. /blog/
url: https://atmorojo.github.io

twitter_username: atmorojo
github_username: atmorojo
instagram_username: atmorojo

# Build Settings
paginate: 10
paginate_path: "posts/:num"

markdown: kramdown

permalink: /:year/:month/:day/:title/

exclude: ["node_modules","Gruntfile.js","package.json"]
incremental: false
highlighter: rouge
gems: [jekyll-paginate, jekyll-feed]
