# Site settings

title: Atmorojo
name: Atmorojo
email: satmo54@gmail.com
description: "I Write Codes and Fancy Letters"

baseurl: "" # the subpath of your site, e.g. /blog/

twitter_username: atmorojo
github_username: atmorojo

url: http://atmorojo.github.io
paginate: 10
paginate_path: "posts/:num"
excerpt_separator: <!--more-->

markdown: redcarpet

redcarpet:
    extensions:  [smart]

gems:
    - jemoji

highlighter: pygments
permalink: /:year/:month/:day/:title/

exclude: [node_modules]
