name: Atmorojo
description: "When I find a nice desctiption, I'll put it here. I promise."

url: http://atmorojo.github.io
paginate: 10
excerpt_separator: <!--more-->

markdown: rdiscount
rdiscount:
    extensions:
        - smart

highlighter: pygments
permalink: /blog/:year/:month/:day/:title/

exclude: [sass, stylesheets, config.rb, Guardfile, sync]
