name: Build and deploy GH Pages

# On every push this script is executed
on: push
      
jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.17.1
      - name: Build and deploy
        run: bash ./build_deploy.sh
        env:
          # Provide personal access token
          TOKEN: ${{ secrets.TOKEN }}
