name: Build and deploy GH Pages

# On every push this script is executed
on: push
      
jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.17.1
      #- name: Checkout main
      #  uses: actions/checkout@v3
      #- name: Build and deploy
      #  uses: shalzz/zola-deploy-action@v0.17.2
        env:
          # Provide personal access token
          TOKEN: ${{ secrets.TOKEN }}
